version: '3'

services:
  database:
    image: 'mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=passwort
    volumes:
      - ./.data/mysql:/var/lib/mysql:rw
    restart: unless-stopped
    # volumes für automatischen import von sql dateien
    # volumes: 
    #   - ../.sql:/docker-entrypoint-initdb.d
  
  # mariadb admin frontend
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080